#! /bin/bash

echo "Name of the Project: "
read -r project
echo "Your name: "
read -r author

echo "Making the project directories"
mkdir $project
cd $project

echo "Making README files"
echo "
$project
========
$author
$(date)

Notes
-----"  >> README.md


echo "Making directories for working"
mkdir data scripts

echo "Making default scripts"

echo "__project__ = $project
__author__ = $author

import numpy as np
np.random.seed(1)

import pandas as pd
from tqdm import tqdm
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import Imputer, MinMaxScaler, RobustScaler, PolynomialFeatures
from sklearn.cross_validation import cross_val_score
from sklearn.grid_search import GridSearchCV

def report(fn):
    def new_fn(*args, **kwargs):
        print('> starting ', fn.__name__)
        results = fn(*args, **kwargs)
        print('> complete ', fn.__name__)
        return results
    return new_fn
" > scripts/main.py

echo "Creating environment"
virtualenv -p python3 env
source env/bin/activate
pip install numpy scipy sklearn pandas tqdm matplotlib pillow seaborn
pip freeze > requirements.txt
echo "Complete"
